source('mcmc_func.R')
args <- commandArgs(trailingOnly=TRUE)
load(args[1])
pp <- cal.residual(par.opt)$res.sigtrend
res.sigtrend <- combine.list(lapply(out$ins.rv,function(k) pp[[k]]))
ee <- cbind(out$all$trv.all,out$res.comb.all[[paste0('sig',Nsig)]],out$all$eRV.all)
ee2 <- cbind(out$all$trv.all,res.sigtrend,out$all$eRV.all)
colnames(ee2) <- colnames(ee) <- c('BJD','RV','eRV')
fout <- paste0('RVresidual/',target,'_rv_white.res')
fout2 <- paste0('RVresidual/',target,'_rv_red.res')
cat(fout,'\n')
write.table(ee,file=fout,quote=FALSE,row.names=FALSE)
cat(fout2,'\n')
write.table(ee2,file=fout2,quote=FALSE,row.names=FALSE)
