modifypar <- function(par){
    Nsig <- length(grep('^per',names(par)))
    ps <- exp(par[paste0('per',1:Nsig)])
    ind <- which(ps<1000)
    if(length(ind)>0){
	par[paste0('K',ind)] <- 0
    }
    par
}

yr2d <- 365.25
##astrometry fit
data.astrometry <- out$astrometry
#par.opt1 <- modifypar(par.opt)
par.opt1 <- par.opt
Ein  <-  RV.kepler(pars.kep=par.opt1,bases=bases,nqp=nqp)$E
#astro0 <- astrometry.kepler(par.opt1,bases=bases,Ein=Ein)$barycenter
if(!any(names(out)=='plx')) out$plx <- out$astrometry$parallax[2]
astro0 <- astrometry.kepler(par.opt1,bases=bases,pa=FALSE)$barycenter
tsim0 <- seq(data.astrometry[1,1],data.astrometry[2,1],length.out=1e3)
tsim <- tsim0-tmin
Nt <- length(tsim)
planet <- astrometry.kepler(par.opt1,tt=tsim,bases=bases,pa=FALSE)$planet
dpmra <- data.astrometry[,'pmra']-astro0[,'pmra']
dpmdec <- data.astrometry[,'pmdec']-astro0[,'pmdec']
dpmras <- c()
dpmdecs <- c()
for(j in 1:Nastro){
    ell <- error.ellipse(dpmra[j],dpmdec[j],cov.astro[4:5,4:5,j],percent=68)
    dpmras <- cbind(dpmras,ell[,1])
    dpmdecs <- cbind(dpmdecs,ell[,2])
}

if(plotf){
screen(Nsig+(i1-1)*5+2)
par(mar=c(margin,2*margin,margin,margin))
plot(dpmra,dpmdec,xlab='',ylab='',xlim=range(planet[,'pmra'],dpmras,dpmra),ylim=range(planet[,'pmdec'],dpmdecs,dpmdec),pch=20,xaxt='n',yaxt='n',col=ell.col)#main='Proper motion fit'
magaxis(1:2)

###MC lines
Nsamp <- 100
if(Nmc>0){
mc <- out$mcmc.opt[[paste0('sig',Nkep)]]
inds <- sample(1:nrow(mc),Nsamp)
Npar <- length(par.opt)
dra.sim <- ddec.sim <- c()

for(j3 in inds){
    pars <- mc[j3,1:Npar]
#    pars1 <- modifypar(pars)
     pars1 <- pars
    planet.mc <- astrometry.kepler(pars1,tt=tsim,bases=bases,pa=FALSE)$planet
    lines(planet.mc[,'pmra'],planet.mc[,'pmdec'],col=fit.col)
    dra.sim <- cbind(dra.sim,planet.mc[,'ra'])
    ddec.sim <- cbind(ddec.sim,planet.mc[,'dec'])
}
}
###
if(i1==Nsig) mtext(side=1,text=expression(Delta*mu[alpha]~'[mas/yr]'),xpd=NA,line=2,cex=1.2*size)
mtext(side=2,text=expression(Delta*mu[delta]~'[mas/yr]'),xpd=NA,line=1.5,cex=1.2*size)
if(dpmra[2]>dpmra[1] & dpmdec[2]>dpmdec[1]) pos <- c(4,2)
if(dpmra[2]<dpmra[1] & dpmdec[2]<dpmdec[1]) pos <- c(2,4)
if(dpmra[2]<dpmra[1] & dpmdec[2]>dpmdec[1]) pos <- c(3,1)
if(dpmra[2]>dpmra[1] & dpmdec[2]<dpmdec[1]) pos <- c(1,3)
lines(planet[,'pmra'],planet[,'pmdec'],col='red',lwd=line.size)
lines(c(planet[1,'pmra'],dpmra[1]),c(planet[1,'pmdec'],dpmdec[1]),col=ell.col[1])
lines(c(planet[Nt,'pmra'],dpmra[2]),c(planet[Nt,'pmdec'],dpmdec[2]),col=ell.col[2])
}
for(j in 1:Nastro){
    lines(dpmras[,j],dpmdecs[,j],col=ell.col[j])
}
text(x=dpmra,y=dpmdec,labels=c('H','G'),col=ell.col,pos=pos)
points(0,0,pch='+')

msini <- K2msini.full(par.opt['K1'],Popt,par.opt['e1'],Ms=Mstar)
mp.opt <- Mp <- msini$mj/sin(par.opt['Inc1'])
Mo <- (par.opt['Mo1']%%(2*pi))*180/pi
inc <- par.opt['Inc1']*180/pi

#####plot position ellipse
dras <- c()
ddecs <- c()
dra <- (data.astrometry[,'ra']-astro0[,'ra'])*3.6e6*cos(data.astrometry[,'dec']/180*pi)#mas
ddec <- (data.astrometry[,'dec']-astro0[,'dec'])*3.6e6#mas
for(j in 1:Nastro){
    ell <- error.ellipse(dra[j],ddec[j],cov.astro[1:2,1:2,j],percent=68)
    dras <- cbind(dras,ell[,1])
    ddecs <- cbind(ddecs,ell[,2])
}
if(plotf){
screen(Nsig+(i1-1)*5+3)
par(mar=c(margin,2*margin,margin,margin))
###GOST plot
reflex.gost <- astrometry.epoch(par.opt,tt=out$gost[,'BJD'],bases=bases)$epoch
kep <- astrometry.kepler(par.opt,bases=bases)
###observed position and proper motion relative to the predicted barycentric position and proper motion
dra.obs <- ((out$astrometry[out$astro.index,'ra']-kep$barycenter[out$astro.index,'ra']))*cos(out$astrometry[out$astro.index,'dec']/180*pi)*3.6e6
ddec.obs <- ((out$astrometry[out$astro.index,'dec']-kep$barycenter[out$astro.index,'dec']))*3.6e6
dpmra.obs <- out$astrometry[out$astro.index,'pmra']-kep$barycenter[out$astro.index,'pmra']
dpmdec.obs <- out$astrometry[out$astro.index,'pmdec']-kep$barycenter[out$astro.index,'pmdec']
dplx.obs <- out$astrometry[out$astro.index,'parallax']-kep$barycenter[out$astro.index,'parallax']
###the position and proper motion reconstructed by a linear fit to gost-based observations generated by accounting for reflex motion
dra.model <- dra.obs+kep$gdr[,1]
ddec.model <- ddec.obs+kep$gdr[,2]
dplx.model <- dplx.obs+kep$gdr[,3]
dpmra.model <- dpmra.obs+kep$gdr[,4]
dpmdec.model <- dpmdec.obs+kep$gdr[,5]

dra.obs.range <- range(sapply(1:length(dra.obs), function(k) dra.obs[k]+dpmra.obs[k]*c(min(out$dtg[[k]]),max(out$dtg[[k]]))))
ddec.obs.range <- range(sapply(1:length(dra.obs), function(k) ddec.obs[k]+dpmdec.obs[k]*c(min(out$dtg[[k]]),max(out$dtg[[k]]))))
dra.model.range <- range(sapply(1:length(dra.model), function(k) dra.model[k]+dpmra.model[k]*c(min(out$dtg[[k]]),max(out$dtg[[k]]))))
ddec.model.range <- range(sapply(1:length(dra.model), function(k) ddec.model[k]+dpmdec.model[k]*c(min(out$dtg[[k]]),max(out$dtg[[k]]))))
dra.range <- range(dra.obs.range,dra.model.range)
ddec.range <- range(ddec.obs.range,ddec.model.range)
####plot
plot(reflex.sim[,'dra'],reflex.sim[,'ddec'],xlab=expression(Delta*alpha*'* [mas]'),ylab=expression(Delta*delta*' [mas]'),type='l',col='grey',xlim=rev(range(reflex.sim[,'dra'],dra.range)),ylim=range(reflex.sim[,'ddec'],ddec.range))
points(0,0,pch='+')
jj <- as.factor(((out$gost[,1]-out$gost[1,1])%%max(Popt))/max(Popt))
cc <- paletteer_c(palette = "viridis::inferno", n = length(jj))
points(reflex.gost[,'dra'],reflex.gost[,'ddec'],col=cc[jj],pch=20)
if(length(out$gdrs)==0) out$gdrs <- c('GDR2','GDR3')
phases <- seq(0,1,by=0.2)
cl <- paletteer_c(palette = "viridis::inferno", n = length(phases))
legend('top',legend=phases,pch=20,col=cl[as.factor(phases)],horiz=TRUE,bty='n',inset=c(0,-0.25),xpd=NA,title='Phase')
ref.epochs <- c()
cols <- c('darkgreen','blue','red')
                                        #    dra.model.comb <- c()
for(k in 1:length(out$astro.index)){
    ttsim <- seq(min(out$dtg[[k]]),max(out$dtg[[k]]),by=0.1)#year
    dras.obs <- dra.obs[k]+dpmra.obs[k]*ttsim
    ddecs.obs <- ddec.obs[k]+dpmdec.obs[k]*ttsim
    lines(dras.obs,ddecs.obs,col=cols[k],lty=2)
    points(dra.obs[k],ddec.obs[k],col=cols[k],pch=1)

    dras.model <- dra.model[k]+dpmra.model[k]*ttsim
    ddecs.model <- ddec.model[k]+dpmdec.model[k]*ttsim
    lines(dras.model,ddecs.model,col=cols[k],lty=1)
    points(dra.model[k],ddec.model[k],col=cols[k],pch=20)
}
                                        #    legend('topright',legend=out$gdrs,col=cols,lty=1,cex=0.8,bty='n',inset=c(-0.23,0),xpd=NA)
legend('top',legend=out$gdrs,col=cols,lty=1,cex=0.8,bty='n',inset=c(0,-0.1),xpd=NA,horiz=TRUE)
trefs <- out$astrometry[out$astro.index,'ref_epoch']
obs <- cbind(dra.obs,ddec.obs,dplx.obs,dpmra.obs,dpmdec.obs)
eobs <- out$astrometry[out$astro.index,c('ra_error','dec_error','parallax_error','pmra_error','pmdec_error')]
model <- cbind(dra.model,ddec.model,dplx.model,dpmra.model,dpmdec.model)
ylabs <- c(expression(Delta*alpha*'* [mas]'),expression(Delta*delta*' [mas]'),'parallax [mas]',expression(Delta*mu[alpha]*' [mas/yr]'),expression(Delta*mu[delta]*' [mas/yr]'))
}

#source('orbit_predict.R')
