source('../../pexo/code/timing_function.R')
source('../../pexo/code/general_function.R')
source('../../pexo/code/sofa_function.R')
source('mcmc_func.R')
load('results/HD16160/HD16160_natural_astro8_Niter10000000_Ncores4_ofac2_Nset6_Esd1_transit0_P28416_acc0.0032_lnlmax-1255.Robj')
res <- read.table('HD16160_comb.txt',header=TRUE)
gst <- read.table('../../pexo/code/out_pexo.txt',header=TRUE)
#par.opt <- read.table('par.opt',header=TRUE)
tsim0 <- seq(2447000, 2462000, by=10)
rv.sim <- RV.kepler(par.opt,tt=tsim0,kep.only=TRUE)$rv
rv.fit <- RV.kepler(par.opt,tt=res[,1],kep.only=TRUE)$rv
tapf <- out$APF$RV[,1]
rv.apf <- RV.kepler(par.opt,tt=tapf,kep.only=TRUE)$rv
tsim <- seq(min(res[,1]),max(res[,1]),by=1)

####convert times
yr.sim0 <- time_Jd2yr(cbind(tsim0,0))
yr.sim <- time_Jd2yr(cbind(tsim,0))
yr <- time_Jd2yr(cbind(res[,1],0))
yrs <- unique(round(yr))
yrs.sim <- unique(round(yr.sim))
yrs.sim0 <- unique(round(yr.sim0))
#yrs <- yrs[yrs%%5==0]
yrs <- yrs[yrs%%2==0]
yrs.sim <- yrs.sim[yrs.sim%%2==0]
yrs.sim0 <- yrs.sim0[yrs.sim0%%2==0]
jds <- rowSums(time_Yr2jd(yrs))
jds.sim <- rowSums(time_Yr2jd(yrs.sim))
jds.sim0 <- rowSums(time_Yr2jd(yrs.sim0))
yr3 <- c(2012,2018,2020,2022)
jd3 <- time_Yr2jd(yr3)

t <- rowSums(gst[,1:2])
gs.pexo <- gst[,'RvgT']+gst[,'RvsT']
gsfun <- approxfun(t,gs.pexo)
gs <- gsfun(res[,1])
gs <- gs-mean(gs)
y1 <- res[,2]-mean(res[,2])
y2 <- y1+gs
y2 <- y2-mean(y2)
ll1 <- sum(dnorm(y1,0,res[,3],log=TRUE))
ll2 <- sum(dnorm(y2,0,res[,3],log=TRUE))
cat('ll1=',ll1,'\n')
cat('ll2=',ll2,'\n')
cat('ll2-ll1=',ll2-ll1,'\n')
fout <- 'gr_fit.pdf'
cat(fout,'\n')
pdf(fout,16,16)
par(mfrow=c(4,4))
ylim <- c(-1,1)
#dts <- c(500,1000,1500,2000)
Ns <- c(50,100,200,300)
#for(dt in dts){
for(N in Ns){
                                        #dbin <- wtb(res[,1],y1,res[,3],dt=dt)
    dbin <- wtb.number(res[,1],y1,res[,3],N=N)
                                        #rbin <- wtb(res[,1],y2,res[,3],dt=dt)
    rbin <- wtb.number(res[,1],y2,res[,3],N=N)
                                        #gbin <- wtb(res[,1],-gs,res[,3],dt=dt)
    gbin <- wtb.number(res[,1],-gs,res[,3],N=N)
    ind <- which(res[,1]>jd3[1])
    sbin <- wtb(res[ind,1],res[ind,2],res[ind,3],dt=600)
                                        #plot(res[,1],res[,2],xlab='BJD',ylab='RV[m/s]',main=paste0('dt=',round(dt),'d'),ylim=ylim)
    plot(res[,1],res[,2],xlab='BJD',ylab='RV[m/s]',main=paste0('bin N=',N),ylim=ylim,col='grey')
    axis(side=3,at=jds,labels=yrs)
    grid(nx=0,ny=NULL,col='grey')
    abline(v=jds,col='grey',lty=3)
    abline(v=jd3,col='blue')
    points(dbin[,1],dbin[,2],col='black',pch=20)
    arrows(dbin[,1],dbin[,2]-dbin[,3],dbin[,1],dbin[,2]+dbin[,3],length=0.05,angle=90,code=3,col='grey')
                                        #points(rbin[,1],rbin[,2],col='blue',pch=20)
                                        #points(gbin[,1],gbin[,2],col='green',pch=20)
    gs.pred <- -gsfun(tsim)
    lines(tsim,gs.pred-mean(gs.pred),col='red')
    points(sbin[,1],sbin[,2],col='red',pch=20)
    arrows(sbin[,1],sbin[,2]-sbin[,3],sbin[,1],sbin[,2]+sbin[,3],length=0.05,angle=90,code=3,col='red')
}

###simulated RV
plot(tsim0,rv.sim,xlab='BJD',ylab='RV[m/s]',main='RV[BT]')
axis(side=3,at=jds.sim0,labels=yrs.sim0,pch=3)
grid(nx=0,ny=NULL,col='grey')
abline(v=jd3,col='blue')
abline(v=jds.sim0,col='grey',lty=3)
plot(tsim0,-gsfun(tsim0),xlab='BJD',ylab='RV[m/s]',main='RV[GS]')
axis(side=3,at=jds.sim0,labels=yrs.sim0)
grid(nx=0,ny=NULL,col='grey')
abline(v=jds.sim0,col='grey',lty=3)
abline(v=jd3,col='blue')
plot(res[,1],res[,2],xlab='BJD',ylab='RV[m/s]',main='RV[raw res]')
points(tapf,out$res.all$sig1$APF,col='red',pch=20)
axis(side=3,at=jds,labels=yrs)
grid(nx=0,ny=NULL,col='grey')
abline(v=jds,col='grey',lty=3)
plot(res[,1],rv.fit,xlab='BJD',ylab='RV[m/s]',main='RV[raw fit]')
points(tapf,rv.apf,col='red',pch=20)
rvfun <- approxfun(t,gst[,'RvST'])
rv.sim0 <- rvfun(tsim0)
rv.pred <- rvfun(res[,1])
rv0 <- mean(rv.pred-rv.fit)
lines(tsim0,rv.sim0-rv0,col='blue')
axis(side=3,at=jds,labels=yrs)
grid(nx=0,ny=NULL,col='grey')
abline(v=jds,col='grey',lty=3)
dev.off()
